# Generated by Django 5.1.1 on 2025-10-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeptModel',
            new_name='Designation',
        ),
    ]
