# Generated by Django 5.1.1 on 2025-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0002_rename_deptmodel_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalmodel',
            name='another_rel',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='salary',
            field=models.PositiveIntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalmodel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personalmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personalmodel',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='designation',
            field=models.CharField(choices=[('manage', 'Manage'), ('ceo', 'CEO'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=100, null=True),
        ),
    ]
