# Generated by Django 5.1.1 on 2025-10-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_remove_personalmodel_another_rel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
