# Generated by Django 5.2.6 on 2025-09-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('roll', models.IntegerField(max_length=50, null=True)),
                ('Admission', models.DateField(null=True)),
            ],
        ),
    ]
