# Generated by Django 5.2.6 on 2025-09-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='Designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
