# Generated by Django 5.2.6 on 2025-09-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teachermodel_designation_teachermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='roll',
            field=models.IntegerField(null=True),
        ),
    ]
