# Generated by Django 5.1.1 on 2025-09-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsonalinfomodel',
            name='another_rel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Relationapp.employeemodel'),
        ),
    ]
