# Generated by Django 5.1.1 on 2025-10-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationapp', '0002_parsonalinfomodel_another_rel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepModel',
            new_name='DepartmentModel',
        ),
        migrations.RenameField(
            model_name='departmentmodel',
            old_name='dept_name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='name',
            new_name='disignation',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='employee_idno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='employee_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BasicInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('another_rel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Relationapp.employeemodel')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employree_info', to='Relationapp.employeemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='ParsonalInfoModel',
        ),
    ]
