# Generated by Django 5.2.6 on 2025-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
