# Generated by Django 5.2.6 on 2025-09-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productmodel_age_productmodel_city_studentmodel_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='age',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='teachermodel',
            old_name='city',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='age',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='added_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='admission_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
