# Generated by Django 5.2.6 on 2025-09-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_age_productmodel_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
