# Generated by Django 5.2.6 on 2025-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_teachermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
