# Generated by Django 5.1.1 on 2025-09-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleModel',
            new_name='ProductModel',
        ),
    ]
