# Generated by Django 5.2.6 on 2025-09-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='cmail',
            new_name='Email',
        ),
    ]
