# Generated by Django 5.2.6 on 2025-09-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_cmail_studentmodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='Email',
            new_name='email',
        ),
    ]
