# Generated by Django 5.2.6 on 2025-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_studentmodel_email_alter_teachermodel_cmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='cmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='cmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
