# Generated by Django 5.2.6 on 2025-09-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_employeemodel_cmail_alter_studentmodel_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='cmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='teachermodel',
            old_name='cmail',
            new_name='email',
        ),
    ]
