# Generated by Django 5.2.6 on 2025-09-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_employeemodel_email_alter_studentmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
