# Generated by Django 5.2.6 on 2025-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_studentmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='email',
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
